# fly.toml app configuration file generated for curatedotfun on 2025-01-15T13:48:42-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'curatedotfun'
primary_region = 'den'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '3000'

[[mounts]]
  source = "litefs"
  destination = "/var/lib/litefs"
  initial_size = '1GB'

[[services]]
  protocol = "tcp"
  internal_port = 8080 # proxy to 3000
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
    
  [[services.http_checks]]
    interval = "30s"
    grace_period = "120s"
    method = "get"
    path = "/health"
    protocol = "http"
    port = 8080
    timeout = "10s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
